"""Markdown export from ResearchResult objects."""
import json
import re
import unicodedata
from datetime import datetime

from beacon.models import Flashcard, ResearchResult


def topic_slug(topic: str) -> str:
    """Convert a topic string into a safe filename slug."""
    normalized = unicodedata.normalize("NFKD", topic)
    ascii_str = normalized.encode("ascii", errors="ignore").decode("ascii")
    lowered = ascii_str.lower()
    slug = re.sub(r"[^a-z0-9]+", "-", lowered)
    slug = slug.strip("-")
    slug = slug[:50]
    slug = slug.strip("-")
    return slug or "research"


def generate_markdown(result: ResearchResult) -> str:
    """Build a complete Markdown document from a ResearchResult."""
    sections: list[str] = []

    # Header
    try:
        dt = datetime.fromisoformat(result.timestamp.replace("Z", "+00:00"))
        date_str = dt.strftime("%Y-%m-%d")
    except (ValueError, AttributeError):
        date_str = result.timestamp

    sections.append(f"# Research: {result.topic}")
    sections.append("")
    sections.append(
        f"**Depth:** {result.depth} | **Sources:** {len(result.sources)} | **Date:** {date_str}"
    )
    sections.append("")

    # Executive Summary
    sections.append("## Executive Summary")
    sections.append("")
    summary = result.artifacts.get("summary")
    if summary is None:
        sections.append("*(Not generated)*")
    else:
        sections.append(str(summary))
    sections.append("")

    # Sources
    sections.append("## Sources (Ranked by Learning Efficiency)")
    sections.append("")
    if not result.sources:
        sections.append("*No sources evaluated.*")
    else:
        sorted_sources = sorted(
            result.sources,
            key=lambda s: s.signals.learning_efficiency_score,
            reverse=True,
        )
        for source in sorted_sources:
            sig = source.signals
            sections.append(f"### {source.title}")
            sections.append("")
            sections.append(f"[{source.url}]({source.url})")
            sections.append("")
            sections.append(f"**Score:** {sig.learning_efficiency_score}/10")
            sections.append(f"**Type:** {sig.content_type}")
            sections.append(f"**Estimated read time:** {sig.time_estimate_minutes} min")
            if sig.recency is not None:
                sections.append(f"**Recency:** {sig.recency}")
            sections.append(f"**Key insight:** {sig.key_insight}")
            sections.append(f"**Topics covered:** {', '.join(sig.coverage)}")
            sections.append("")
    sections.append("")

    # Concept Map
    sections.append("## Concept Map")
    sections.append("")
    concept_map = result.artifacts.get("concept_map")
    if concept_map is None:
        sections.append("*(Not generated)*")
    else:
        sections.append(str(concept_map))
    sections.append("")

    # Flashcards
    sections.append("## Flashcards")
    sections.append("")
    flashcards = result.artifacts.get("flashcards")
    if flashcards is None:
        sections.append("*(Not generated)*")
    else:
        cards = _parse_flashcards(flashcards)
        if cards is not None:
            for i, (q, a) in enumerate(cards, 1):
                sections.append(f"**Q{i}:** {q}")
                sections.append(f"**A{i}:** {a}")
                sections.append("")
        else:
            sections.append(str(flashcards))
    sections.append("")

    # Resources
    sections.append("## Resources")
    sections.append("")
    resources = result.artifacts.get("resources")
    if resources is None:
        sections.append("*(Not generated)*")
    else:
        sections.append(_render_resources(resources))
    sections.append("")

    # Footer
    sections.append("---")
    sections.append("")
    sections.append("*Generated by Beacon Research Agent*")
    sections.append("")

    return "\n".join(sections)


def _parse_flashcards(data) -> list[tuple[str, str]] | None:
    """Parse flashcard data from various formats into (question, answer) pairs."""
    if isinstance(data, list):
        pairs = []
        for item in data:
            if isinstance(item, Flashcard):
                pairs.append((item.question, item.answer))
            elif isinstance(item, dict) and "question" in item and "answer" in item:
                pairs.append((item["question"], item["answer"]))
            else:
                return None
        return pairs

    if isinstance(data, str):
        try:
            parsed = json.loads(data)
        except json.JSONDecodeError:
            return None
        if isinstance(parsed, list):
            return _parse_flashcards(parsed)
        return None

    return None


def _render_resources(data) -> str:
    """Render resources data to readable markdown."""
    if isinstance(data, str):
        try:
            parsed = json.loads(data)
        except json.JSONDecodeError:
            return data
        return _render_resources(parsed)

    if isinstance(data, list):
        lines = []
        for item in data:
            if isinstance(item, dict):
                parts = []
                if "title" in item:
                    parts.append(f"**{item['title']}**")
                if "url" in item:
                    parts.append(f"[{item['url']}]({item['url']})")
                if "description" in item:
                    parts.append(item["description"])
                lines.append("- " + " - ".join(parts) if parts else f"- {item}")
            else:
                lines.append(f"- {item}")
        return "\n".join(lines)

    if isinstance(data, dict):
        lines = []
        for key, value in data.items():
            if isinstance(value, list):
                items = ", ".join(str(v) for v in value)
                lines.append(f"**{key}:** {items}")
            else:
                lines.append(f"**{key}:** {value}")
        return "\n".join(lines)

    return str(data)
