"""Tests for server.export module."""
import json

from beacon.models import EvaluatedSource, Flashcard, IntelligenceSignals, ResearchResult
from server.export import generate_markdown, topic_slug


# ─── Helper ───────────────────────────────────────────────────


def _make_source(title: str, score: int, **kw) -> EvaluatedSource:
    """Create an EvaluatedSource with minimal boilerplate."""
    return EvaluatedSource(
        url=kw.get("url", f"https://example.com/{title.lower().replace(' ', '-')}"),
        title=title,
        snippet=kw.get("snippet", f"Snippet for {title}"),
        signals=IntelligenceSignals(
            learning_efficiency_score=score,
            content_type=kw.get("content_type", "tutorial"),
            time_estimate_minutes=kw.get("time_estimate", 15),
            recency=kw.get("recency", "2024"),
            key_insight=kw.get("key_insight", f"Key insight about {title}"),
            coverage=kw.get("coverage", ["topic-a", "topic-b"]),
        ),
    )


def _make_result(**kw) -> ResearchResult:
    """Create a ResearchResult with sensible defaults."""
    return ResearchResult(
        topic=kw.get("topic", "Machine Learning"),
        depth=kw.get("depth", "standard"),
        sources=kw.get("sources", [_make_source("Default Source", 7)]),
        artifacts=kw.get("artifacts", {}),
        session_id=kw.get("session_id", "test-session"),
        timestamp=kw.get("timestamp", "2024-06-15T10:00:00Z"),
    )


# ─── Happy path ───────────────────────────────────────────────


def test_header_includes_topic_depth_date_source_count():
    """Header contains topic, depth, source count, and date."""
    sources = [_make_source("S1", 5), _make_source("S2", 8), _make_source("S3", 3)]
    result = _make_result(sources=sources)
    md = generate_markdown(result)
    assert md.startswith("# Research: Machine Learning")
    assert "standard" in md
    assert "3" in md  # source count
    assert "2024-06-15" in md  # date


def test_includes_executive_summary():
    """Executive Summary section appears with summary text."""
    result = _make_result(artifacts={"summary": "This is the summary text."})
    md = generate_markdown(result)
    assert "## Executive Summary" in md
    assert "This is the summary text." in md


def test_includes_sources_with_signals():
    """Sources section includes all intelligence signal fields."""
    source = _make_source(
        "Deep Learning Guide",
        score=9,
        content_type="tutorial",
        time_estimate=20,
        recency="2024",
        key_insight="Transformers are key",
        coverage=["neural-nets", "attention"],
    )
    result = _make_result(sources=[source])
    md = generate_markdown(result)
    assert "## Sources" in md
    assert "Deep Learning Guide" in md
    assert "9/10" in md
    assert "tutorial" in md
    assert "20 min" in md
    assert "2024" in md
    assert "Transformers are key" in md
    assert "neural-nets" in md
    assert "attention" in md
    assert "example.com" in md  # URL appears


def test_sources_ordered_by_score_descending():
    """Sources are sorted by learning_efficiency_score descending."""
    sources = [
        _make_source("Medium", 5),
        _make_source("Best", 9),
        _make_source("Worst", 3),
    ]
    result = _make_result(sources=sources)
    md = generate_markdown(result)
    best_pos = md.index("Best")
    medium_pos = md.index("Medium")
    worst_pos = md.index("Worst")
    assert best_pos < medium_pos < worst_pos


def test_includes_concept_map():
    """Concept Map section appears with content."""
    result = _make_result(artifacts={"concept_map": "- Root\n  - Child1\n  - Child2"})
    md = generate_markdown(result)
    assert "## Concept Map" in md
    assert "- Root" in md
    assert "- Child1" in md


def test_includes_flashcards_from_objects():
    """Flashcards section formats Flashcard objects as Q&A."""
    cards = [Flashcard(question="What is ML?", answer="Machine Learning")]
    result = _make_result(artifacts={"flashcards": cards})
    md = generate_markdown(result)
    assert "## Flashcards" in md
    assert "What is ML?" in md
    assert "Machine Learning" in md


def test_includes_resources():
    """Resources section renders JSON-string resources."""
    resources = json.dumps([{"title": "Resource 1", "url": "https://r1.com"}])
    result = _make_result(artifacts={"resources": resources})
    md = generate_markdown(result)
    assert "## Resources" in md
    assert "Resource 1" in md


def test_includes_footer():
    """Footer with 'Generated by Beacon Research Agent' appears."""
    result = _make_result()
    md = generate_markdown(result)
    assert "Generated by Beacon Research Agent" in md


# ─── Edge cases / defensive handling ─────────────────────────


def test_missing_summary_shows_not_generated():
    """Missing summary artifact shows 'Not generated' placeholder."""
    result = _make_result(artifacts={})
    md = generate_markdown(result)
    assert "Not generated" in md


def test_missing_concept_map_shows_not_generated():
    """Missing concept_map shows 'Not generated'."""
    result = _make_result(artifacts={})
    md = generate_markdown(result)
    assert "## Concept Map" in md
    assert "Not generated" in md


def test_none_artifact_value_shows_not_generated():
    """None artifact value treated same as missing."""
    result = _make_result(artifacts={"summary": None})
    md = generate_markdown(result)
    assert "Not generated" in md


def test_empty_sources_list():
    """Empty sources list shows appropriate message."""
    result = _make_result(sources=[])
    md = generate_markdown(result)
    assert "No sources" in md.lower() or "no sources" in md.lower()


def test_flashcards_as_flashcard_objects():
    """Flashcard objects are formatted correctly."""
    cards = [Flashcard(question="Q?", answer="A")]
    result = _make_result(artifacts={"flashcards": cards})
    md = generate_markdown(result)
    assert "Q?" in md
    assert "A" in md


def test_flashcards_as_json_string():
    """JSON string flashcards are parsed and formatted."""
    cards_json = json.dumps([{"question": "Q?", "answer": "A"}])
    result = _make_result(artifacts={"flashcards": cards_json})
    md = generate_markdown(result)
    assert "Q?" in md
    assert "A" in md


def test_resources_as_json_string():
    """JSON string resources are parsed and rendered."""
    resources = json.dumps({"links": ["url1"]})
    result = _make_result(artifacts={"resources": resources})
    md = generate_markdown(result)
    assert "url1" in md


def test_malformed_json_resources_fallback_to_raw():
    """Malformed JSON in resources falls back to raw text."""
    result = _make_result(artifacts={"resources": "not valid json {"})
    md = generate_markdown(result)
    assert "not valid json {" in md


def test_unknown_artifact_keys_ignored():
    """Unknown artifact keys don't appear in output."""
    result = _make_result(artifacts={"summary": "text", "unknown_key": "data"})
    md = generate_markdown(result)
    assert "unknown_key" not in md
    assert "text" in md


# ─── topic_slug ───────────────────────────────────────────────


def test_slug_lowercase_hyphens():
    """Slug is lowercase with hyphens."""
    assert topic_slug("Machine Learning") == "machine-learning"


def test_slug_handles_unicode():
    """Unicode chars are normalized to ASCII."""
    slug = topic_slug("Réseau Neuronal")
    assert slug.isascii()
    assert "reseau" in slug


def test_slug_removes_special_chars():
    """Special/unsafe characters are removed."""
    slug = topic_slug("C++ / C# <Programming>")
    assert "<" not in slug
    assert ">" not in slug
    assert "/" not in slug
    assert "#" not in slug


def test_slug_truncates_to_50():
    """Slug is truncated to 50 characters max."""
    slug = topic_slug("a" * 100)
    assert len(slug) <= 50


def test_slug_strips_leading_trailing_hyphens():
    """Leading and trailing hyphens are stripped."""
    slug = topic_slug("---hello---")
    assert slug == "hello"


def test_slug_collapses_multiple_hyphens():
    """Multiple consecutive hyphens are collapsed to one."""
    slug = topic_slug("hello   world!!!test")
    assert "hello-world-test" == slug


def test_slug_empty_input_returns_fallback():
    """Pure non-ASCII input that produces empty slug returns 'research' fallback."""
    slug = topic_slug("\u4e16\u754c")  # Chinese characters
    assert slug == "research"


# ─── Integration with conftest fixtures ───────────────────────


def test_generate_markdown_with_conftest_fixture(sample_research_result):
    """generate_markdown works with the shared sample_research_result fixture."""
    md = generate_markdown(sample_research_result)
    assert "# Research:" in md
    assert sample_research_result.topic in md
    assert "## Executive Summary" in md
    assert "## Sources" in md
    assert "Generated by Beacon Research Agent" in md
